/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTutorRouteImport } from './routes/_app.tutor'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppQuizIndexRouteImport } from './routes/_app.quiz.index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app.library.index'
import { Route as AppQuizTopicRouteImport } from './routes/_app.quiz.$topic'
import { Route as AppLibraryIdRouteImport } from './routes/_app.library.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizIndexRoute = AppQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizTopicRoute = AppQuizTopicRouteImport.update({
  id: '/quiz/$topic',
  path: '/quiz/$topic',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIdRoute = AppLibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/learn': typeof AppLearnRoute
  '/tutor': typeof AppTutorRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/quiz/$topic': typeof AppQuizTopicRoute
  '/library/': typeof AppLibraryIndexRoute
  '/quiz/': typeof AppQuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/learn': typeof AppLearnRoute
  '/tutor': typeof AppTutorRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/quiz/$topic': typeof AppQuizTopicRoute
  '/library': typeof AppLibraryIndexRoute
  '/quiz': typeof AppQuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/library/$id': typeof AppLibraryIdRoute
  '/_app/quiz/$topic': typeof AppQuizTopicRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/quiz/': typeof AppQuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/learn'
    | '/tutor'
    | '/library/$id'
    | '/quiz/$topic'
    | '/library/'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/learn'
    | '/tutor'
    | '/library/$id'
    | '/quiz/$topic'
    | '/library'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/coach'
    | '/_app/dashboard'
    | '/_app/learn'
    | '/_app/tutor'
    | '/_app/library/$id'
    | '/_app/quiz/$topic'
    | '/_app/library/'
    | '/_app/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/': {
      id: '/_app/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof AppQuizIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/$topic': {
      id: '/_app/quiz/$topic'
      path: '/quiz/$topic'
      fullPath: '/quiz/$topic'
      preLoaderRoute: typeof AppQuizTopicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$id': {
      id: '/_app/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AppLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLearnRoute: typeof AppLearnRoute
  AppTutorRoute: typeof AppTutorRoute
  AppLibraryIdRoute: typeof AppLibraryIdRoute
  AppQuizTopicRoute: typeof AppQuizTopicRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppQuizIndexRoute: typeof AppQuizIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLearnRoute: AppLearnRoute,
  AppTutorRoute: AppTutorRoute,
  AppLibraryIdRoute: AppLibraryIdRoute,
  AppQuizTopicRoute: AppQuizTopicRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppQuizIndexRoute: AppQuizIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
